FIX40:
  '8': 'BeginString'
  '9': 'BodyLength'
  '35': 'MsgType'
  '34': 'MsgSeqNum'
  '49': 'SenderCompID'
  '56': 'TargetCompID'
  '52': 'SendingTime'
  '1': 'Account'
  '11': 'ClOrdID'
  '38': 'OrderQty'
  '40': 'OrdType'
  '44': 'Price'
  '54': 'Side'
  '55': 'Symbol'
  '59': 'TimeInForce'
  '60': 'TransactTime'
  '150': 'ExecType'
  '151': 'LeavesQty'
  '17': 'ExecID'
  '37': 'OrderID'
  '58': 'Text'
  '6': 'AvgPx'
  '14': 'CumQty'
  '39': 'OrdStatus'
  '41': 'OrigClOrdID'
  '20': 'ExecTransType'
  '198': 'SecondaryClOrdID'

FIX41:

FIX42:
  '75': 'TradeDate'
  '129': 'Issuer'
  '142': 'SenderLocationID'
  '144': 'TargetLocationID'
  '168': 'EffectiveTime'
  '432': 'FirmTradeID'

FIX43:
  '31': 'LastPx'
  '32': 'LastQty'

FIX44:
  '8': 'BeginString'
  '9': 'BodyLength'
  '35': 'MsgType'
  '34': 'MsgSeqNum'
  '49': 'SenderCompID'
  '56': 'TargetCompID'
  '52': 'SendingTime'
  '1': 'Account'
  '11': 'ClOrdID'
  '38': 'OrderQty'
  '40': 'OrdType'
  '44': 'Price'
  '54': 'Side'
  '55': 'Symbol'
  '59': 'TimeInForce'
  '60': 'TransactTime'
  '150': 'ExecType'
  '151': 'LeavesQty'
  '17': 'ExecID'
  '37': 'OrderID'
  '58': 'Text'
  '6': 'AvgPx'
  '14': 'CumQty'
  '39': 'OrdStatus'
  '41': 'OrigClOrdID'
  '20': 'ExecTransType'
  '75': 'TradeDate'
  '129': 'Issuer'
  '142': 'SenderLocationID'
  '144': 'TargetLocationID'
  '168': 'EffectiveTime'
  '432': 'FirmTradeID'
  '31': 'LastPx'
  '32': 'LastQty'
  '198': 'SecondaryClOrdID'
  '127': 'DKReason'